baseURL = "http://localhost:1313/"
languageCode = "en"
defaultContentLanguage = "en"
title = "yzhe819"                        # site title                     # ç½‘ç«™æ ‡é¢˜
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡\æ—¥æ–‡\éŸ©æ–‡
summaryLength = 100
paginate = 4                           # shows the number of articles   # é¦–é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
enableEmoji = true
googleAnalytics = ""                   # your google analytics id       # Googleç»Ÿè®¡ä»£ç 
disqusShortname = ""                   # your discuss shortname         # Disqusè¯„è®ºç³»ç»Ÿä»£ç 

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                      # å¿…éœ€
  name = "yzhe819"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu               # é…ç½®èœå•
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "yzhe819's Blog"                                       # site's subTitle              # ç½‘ç«™äºŒçº§æ ‡é¢˜
  footerSlogan = " "                                   # site's footer slogan         # ç½‘ç«™é¡µè„šæ ‡è¯­
  keywords = ["yzhe819", "zozo"]                                   # site's keywords              # ç½‘ç«™å…³é”®å­—
  description = "ğŸ’–"                        # site's description           # ç½‘ç«™æè¿°
  enableMathJax = true                                                 # enable mathjax               # æ˜¯å¦ä½¿ç”¨mathjaxï¼ˆæ•°å­¦å…¬å¼ï¼‰
  enableSummary = true                                                 # display the article summary  # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æ‘˜è¦
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
# ç¤¾äº¤åœ°å€é…ç½®
[social]
  github = "https://github.com/yzhe819"
  # twitter = " "
  # facebook = " "
  # weibo = " "
  # instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
